# Generated by Django 5.2.9 on 2025-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='metadata',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='version',
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
