# Generated by Django 5.2.9 on 2025-12-05 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_rename_metadata_pipeline_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['user', 'name'], name='pipelines_p_user_id_83a3be_idx'),
        ),
    ]
