# apps/orbits/tasks.py
from celery import shared_task
from asgiref.sync import async_to_sync
from .models import Orbit
from apps.ai.groq_client import generate_full_project


@shared_task(bind=True, max_retries=3, default_retry_delay=30)
def generate_project_task(self, orbit_id, prompt, context=""):
    """
    Celery task that generates a full project using Gemini AI.
    """
    try:
        orbit = Orbit.objects.get(id=orbit_id)
    except Orbit.DoesNotExist:
        print(f"Orbit {orbit_id} not found")
        return

    orbit.status = 'processing'
    orbit.save()

    try:
        # THIS IS THE ONLY CORRECT WAY TO CALL OUR ASYNC FUNCTION FROM CELERY
        result = async_to_sync(generate_full_project)(prompt)  # Only 1 argument!

        # Save the generated project
        orbit.artifacts = {
            "project_name": result.get("project_name", "my-project"),
            "stack": result.get("stack", "Django + React"),
            "explanation": result.get("explanation", "Project generated by AI"),
            "files": result.get("files", [])
        }
        orbit.status = 'completed'
        orbit.save()

        print(f"Project generated successfully for orbit {orbit_id}")

    except Exception as e:
        print(f"Generation failed: {e}")
        orbit.status = 'failed'
        orbit.error_message = str(e)
        orbit.artifacts = {"error": f"Generation failed: {str(e)}"}
        orbit.save()

        # Optional: retry on rate limit
        if "quota" in str(e).lower() or "429" in str(e):
            raise self.retry(exc=e)

        # Re-raise so Celery logs it
        raise