# Generated by Django 5.2.9 on 2025-12-05 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orbit',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['user', 'created_at'], name='orbits_orbi_user_id_fb638e_idx'),
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['status'], name='orbits_orbi_status_4d116e_idx'),
        ),
    ]
