# Generated by Django 5.2.9 on 2025-12-05 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDLCNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('Requirement', 'Requirement'), ('Analysis', 'Analysis'), ('Design', 'Design'), ('Implementation', 'Implementation'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Maintenance', 'Maintenance')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
